name: "Terraform Github Actions"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform Workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

      - name: "Terraform plan"
        id: plan
        run: terraform plan

      - name: "Terraform apply"
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply
        