name: "Terraform Github Actions"
on:
  pull-request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform init"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
      uses: actions/checkout@master
      - name: "Terraform Initialization"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.0.5
        tf_actions_subcommand: "init"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}